language: node_js
node_js:
- '0.12'
addons:
  ssh_known_hosts: tommymcgahee.com
before_install:
- openssl aes-256-cbc -K $encrypted_d7b7c69cad8c_key -iv $encrypted_d7b7c69cad8c_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- npm install -g bower grunt-cli
- bower install
- npm install
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
notifications:
  hipchat:
    rooms:
      secure: NdpYUG7jxJatTN6zD3UQdFQrM+/ccUaCCZNKqQo2RNqMYSVvlIq5NdVAk783N74mEL+rnZQWWE3I0qBWf5wbSszF0cm8EtIOWYSnDrBgjXG7Maoh0QqlGOuar77BQmj+JBuB13IcNfW9sgniFs0eLGlAGLqsNan1O6uXc3RmzZrRv6OAsvMtNsHbi+14539tOVjqq5e3AesiSZ7mo3EoJuW8WQ8RndVueTW7nzlV7GFaH5R4aQud0ycxVpDHHerW8lAKsGyeEm7iPb6YVJD2BvIoxWpBueiqxvtDbIYfD4O8OZMGJc724Vo2EgrTagIwNHZmqoueXDboWlg0krNZO854HNBwApIZiD81SGft384qn6N1utzWB9HvZ2q8h7pcHsUDRpcvGjjdrDW+59IKPBtNSBJVLkVZacDknSrSsAjh6nIL3GWIovsHKUcu2o3+wozqtp3ymiE+CmM+BCWKFO2CFrBxWvn0JhRh3kOhxr3d1kh0Ly8pJwtB3H7P3G9XMDCCKShpM7Yzrfv6tGHGvdu+hfEzvJGMtlHe/YV0+w6pI+BHJAsQLTIwRayJ1E1gmQeIIR3PGYLDFvWgEB4x3TXfPUZ5nm1t9aXVNL/hwXCGWExFLEHdFMixlSzH5GR+Z7m1z7txs1USJkGBdMSnDHN1z+if/TyVDn3o/pCHPUM=
