language: node_js
node_js:
- '0.12'
addons:
  ssh_known_hosts: tommymcgahee.com
before_install:
- openssl aes-256-cbc -K $encrypted_717d6877ac26_key -iv $encrypted_717d6877ac26_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- npm install -g bower grunt-cli
- bower install
- npm install
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
notifications:
  hipchat:
    rooms:
      secure: H08GAxa57zLggZ1wBz/j77WAFNhwtJWE/VuL9deMPtctQdveORrzqIY7BKl82FPIpCwHVU7Phglpm2zyeRuAiNfyQ9bf4wkztAIn8Xb1lKsFATBBvE0KQBWKFsImgobo5fE5rJgHOnmrU/u4CjgDFrGgOBSVQUCQrg5kU3zTEum8+IHZDaoVqJR8NE2Nvvbk9w6r1SoneilUHe0VT+DnH+9Tx48C8E6EOXcckdr3S0uJ3EwDar4vf1Emg5D6GqE1BOuTzWhHE9+TSehajuPjGneX82AIk9fIvNRDfyIOjYX21OhPslAoVgbXy+m2a6NF9d6SAngI9SX1rRzQwjLE151wZwhq36nXqMxnZjeLndH856Y0GIrwNAYbnh4D7eRzxgSU+KupSDz2hYe1qXnSAZjy1777Z6v/yjbbmxuXVMk7MxLjDNFbVDXN1aExk10f8KgjfXFTNyF+pxj47MXUgNznFgDojl7kUXakLbBQBBhD2nla5unUSaqjWrXvM18e2CF0mZHhdsAtDAe4cxweyxIg+OTZx+6U1O2kfKekPJntGfQb+Q88HEuGYASTXDNLF/X97nef6Zy2opuTLVGoutdArmz0GEnnY91dVjmwdcS2Mq/vympPumzN36Bpb8d9UauZUtjGoEy/1D7NPzEI3j7eAowJt44FhRmV4uHDdNQ=
