language: node_js
node_js:
- '0.12'
addons:
  ssh_known_hosts: tommymcgahee.com
before_install:
- openssl aes-256-cbc -K $encrypted_717d6877ac26_key -iv $encrypted_717d6877ac26_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- npm install -g bower grunt-cli
- bower install
- npm install
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
notifications:
  hipchat:
    rooms:
      secure: YaFlKYartY4C8d6dzRepRNCo3ZR7UhpKtkUFJXU+no8Tzjr+/2I5620rn3o2zuN//sQ+dG+BB0eIomiOjBvtwRxDD9qTngEhcabAArwYGrM1wmlYr2tIfCDRFd+R2u6P24XgoLjTn2aJNCmvAEpKE5/XdWJQwI00OmyK7N+JzZayTAx6r79Y5rpHscs0lSZb2LvsGUrOhbNyQ+6nx2R3nHX/vAi2D29KpgHIO2qT1RaZD5IV9wsUefEMXdfnOUJqrTNE1oOkORgPYzkNq32bqQ27qx1zmEG21x2/CUBUWdAHeqrm+reuLpOXkPhgaeYhER4LUQKv6Q/3+d8Zd4PWnl7LX5elUvKTH76CkvNC8ZHgP+lWoWcm6TIMG1zLISZ1C+j4oWFNKxnTRfSke/r7U5N+3islM+pKHIGSpx/14NbtOgQQSLOMvTkSu1vtFwyw+U7WFJMJc43I8cmsN1bRPHZZV1lftPOF03kt1PxbdG7MVuoMCa5thJNyJxtbC/0fr+XNqNggvJXmG7g1fQqqZwQYCYF7m+agvW+YAsI9txUqaK5b2ZT2fcjS8VU2CD4pOvLhuEVFVuNJ2wMntPKbVGa3L5579o9QCSw2FfQKcL2lkP2OUecsphWPROn7gjOWcp+7/dHxypBB8gysZW1imP42OPHcJX8CCRLsDyEAT3w=