language: node_js
node_js:
- '0.12'
addons:
  ssh_known_hosts: tommymcgahee.com
before_install:
- openssl aes-256-cbc -K $encrypted_717d6877ac26_key -iv $encrypted_717d6877ac26_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- npm install -g bower grunt-cli
- bower install
- npm install
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
notifications:
  hipchat:
    rooms:
      secure: jNOIikhM3/xmAJ7wEftoapzmxlvL/ZLTLGVIvlfgQt1tiqx0JqsGhDkx2yw0OwEZ8hyhv1g/l6ZzJdTORNq/6K2rw748YGSAogomMs+vpPZnszpOLIPoIrXy0GU0z6bt8/DfduTDghwCwG0H1+faDs0JUBglmV06pCmPnwgU9S5ddNQbFKM2vKIMcxlmYiOIb7DwhIwNKbKK4W+/aufBPpcHc/exhu8NU3fGVNa4yamM+H+r9kWakN9blEMHTjZFN1xFHv35Bnd1jrF589DieLBo6AdurfxRvkiEJL7t14tuvvfQpEpaT8GiVKBlrEEWh18sBwkAopFwPINl50x+5Q0juzmp5KuvbuKlPzw+pqAtmVfvCbMYWGPoHLx3xXeyeeIMrc7PeNNqor5FmRL6QwRJyNwSSm/s/LstW2Tfie511kluCI/nOOqkowMdsz15bAyyAezICfjT0u808OS/DvtqGP4LAR+Ghm2FIYTkJxoE+mttlavpqLi8G+8lpLJLT3RiMmCg1VbyUo8kSSZ6jr2Nvn+Pt8wD4AF3A3mGrFcgcGnMMQ95muPkXVn7Ew7AvfFlhrKBGovdlQwCiTXYzDfUwQd2ow2VruVqUtK9EPesTW8CU5lwuofWpprS2faI1rxVYDs63IP5/DQJDbPsaRTTkx3I9irf5iMOjyc2NjU=
