language: node_js
node_js:
- '0.12'
install:
- npm install -g bower grunt-cli
- bower install
- npm install
notifications:
  hipchat:
    rooms:
      secure: ueRI9dYW21YxALW687RJmSgTe5llVH/ilthNsiiymI/eubJ1hKeAhmfV2BLpa4+fvb9riPv9LR7xt8FbkZzeV6YO7Q+7ka8xgH0KBJWZfjWcEH2uk3wATG9ezzmMJ2A8/cnicLO6d3V0M08V75KsjJtROhdy6ADFb4M7ae7kjjrA5COko2HTempQk2sLnO+T0cu791wAOBx3NlhFWLvTsoA8yXLP2U63fnlY9sS69rUjEROuy5xu3aZKdZEE6LlMSNgCT6eUNwlVDKeqfp0GlkeqDB0ZzaWwC9oQQqEee/R3lpyyjdqRVkwa8a4Uv78/wQ2/fz775GL7aK6d0BBeKLARH0VvaX0e81yktHcOPxtkvtOv/yIa/QTbgjn82qYZho7TfEiZ7WqsVxMJi+aOoteFXaBhngDMDXRA2073+ksMwLhP46OlDiwaELZO/MeEA5K5hkQv0lEyR1TZvjo5g6CGMKe5bLDfabpV2V79veoSbkNw5N8oS9Jw8Wje2xKcgkHTP1yl6TkUk2GwvUIMwvaG7TUXzDgqxYOC5KR7NfpvW7ommdnUQPY6bt75bC0PQFZbRy0dZXXNZth6fxHgBWkvCt0DD4lo28ylbFXbzQlrvSwuBWDabbeSdihrZ8jC+EHgPFMpFbWNEOYZf8mKikZBUkTuxxNYS7jqtPvOsXE=
before_install:
- openssl aes-256-cbc -K $encrypted_717d6877ac26_key -iv $encrypted_717d6877ac26_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
addons:
  ssh_known_hosts: tommymcgahee.com
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key # this key should have push access
  - ssh-add .travis/deploy_key
  - git remote add production deploy@tommymcgahee.com:interview
  - cd dist
  - git add * 
  - git commit -m "Deployed to production server"
  - git config --global push.default simple
  - git push --force --quiet production master